### ISSUE TITLE
Error while provisioning as Deployment template on Azure : 

### ISSUE THREAD

**Issue by gkgth** [Azure/azure-devops-utils#73] opened 2018-05-24 18:31 UTC
Ubuntu 14.045
Error : 
=========
imported\ngpg: Total number processed: 1\ngpg: imported: 1 (RSA: 1)\nW: GPG error: https://apt-mo.trafficmanager.net wheezy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF\nE: There are problems and -y was used without --force-yes\

script : 301-jenkins-acr-spinnaker-k8s.sh

function install_az() {
  if !(command -v az >/dev/null); then
    apt-get update && sudo apt-get install -y libssl-dev libffi-dev python-dev
    echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/azure-cli/ whh
eezy main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
    apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
    apt-get install -y apt-transport-https
    apt-get -y update && apt-get install -y azure-cli
  fi
}

**Comment by yungezz** [comment] 2018-12-05 08:04
the issue is fixed in https://github.com/Azure/jenkins already. This repo is not active  jenkins solution template/quick start template repo, but https://github.com/Azure/jenkins. Pls try it and file issue at that repo. Thanks.

**Closed as completed** 2018-12-05 08:10 UTC
